config/routes.rb
Rails.application.routes.draw do
  resources :emails
  resources :epostcards
  get 'deliver', to: 'emails#deliver', as: :deliver_epostcard
  resources :pages
  resources :lodgings
  devise_for :users
  get 'home/index'
  root to: "home#index"
  resources :users

end

app/models/epostcard.rb
class Epostcard < ApplicationRecord
  belongs_to :page
  has_many :emails
  mount_uploader :main_image, ImageUploader
end

app/controllers/epostcards_controller.rb
class EpostcardsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_epostcard, only: [:show, :edit, :update, :destroy]
  layout 'epostcard'

  def index
    @epostcards = Epostcard.all
  end

  def show
    # make some sample data for the previews
    @lodging = Lodging.first
    @email = Email.first
  end

  def new
    @epostcard = Epostcard.new
  end

  def edit
  end

  def create
    @epostcard = Epostcard.new(epostcard_params)

    respond_to do |format|
      if @epostcard.save
        format.html { redirect_to page_path(params[:epostcard][:page_id]), notice: 'Epostcard was successfully created.' }
        format.json { render :show, status: :created, location: @epostcard }
      else
        format.html { render :new }
        format.json { render json: @epostcard.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @epostcard.update(epostcard_params)
        format.html { redirect_to @epostcard, notice: 'Epostcard was successfully updated.' }
        format.json { render :show, status: :ok, location: @epostcard }
      else
        format.html { render :edit }
        format.json { render json: @epostcard.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @epostcard.destroy
    respond_to do |format|
      format.html { redirect_to epostcards_url, notice: 'Epostcard was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_epostcard
      @epostcard = Epostcard.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def epostcard_params
      params.require(:epostcard).permit(:name, :main_image, :page_id)
    end
end

app/views/epostcards/_form.html.haml
= form_for @epostcard do |f|
  - if @epostcard.errors.any?
    #error_explanation
      %h2= "#{pluralize(@epostcard.errors.count, "error")} prohibited this epostcard from being saved:"
      %ul
        - @epostcard.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_area :name
  .field
    = f.label :main_image
    = f.file_field :main_image
  .field
    = f.label :page
    = f.text_field :page
  .actions
    = f.submit 'Save'

app/views/epostcards/edit.html.haml
%h1 Editing epostcard

= render 'form'

= link_to 'Show', @epostcard
\|
= link_to 'Back', epostcards_path

app/views/epostcards/index.html.haml
%h1 Listing epostcards

%table
  %thead
    %tr
      %th Name
      %th Main image
      %th Page
      %th
      %th
      %th

  %tbody
    - @epostcards.each do |epostcard|
      %tr
        %td= epostcard.name
        %td epostcard.main_image
        %td= epostcard.page
        %td= link_to 'Show', epostcard
        %td= link_to 'Edit', edit_epostcard_path(epostcard)
        %td= link_to 'Destroy', epostcard, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Epostcard', new_epostcard_path

app/views/epostcards/new.html.haml
%h1 New epostcard

= render 'form'

= link_to 'Back', epostcards_path

app/views/epostcards/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @epostcard.name
%p
  %b Main image:
  = @epostcard.main_image.url
%p
  %b Page:
  = @epostcard.page

= link_to 'Edit', edit_epostcard_path(@epostcard)
\|
= link_to 'Back', epostcards_path